name: Build JavaFX App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build jlink (Linux)
        run: mvn clean javafx:jlink
        working-directory: AssessX

      - name: Upload Linux build
        uses: actions/upload-artifact@v4
        with:
          name: linux-app
          path: AssessX/target/app

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build project
        run: mvn clean package
        working-directory: AssessX

      - name: Build Windows exe
        run: |
          jpackage `
            --name AssessX `
            --input AssessX/target `
            --main-jar AssessX-1.0-SNAPSHOT.jar `
            --main-class com.assessx.assessx.MainApplication `
            --type exe

      - name: Upload Windows build
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: AssessX/*.exe

  build-macos:
    runs-on: macos-latest
  
    steps:
      - uses: actions/checkout@v4
  
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
  
      - name: Build project
        run: mvn clean package
        working-directory: AssessX
  
      - name: Build macOS app
        run: |
          jpackage \
            --name AssessX \
            --input AssessX/target \
            --main-jar AssessX-1.0-SNAPSHOT.jar \
            --main-class com.assessx.assessx.MainApplication \
            --type app-image  
